# home/hyprland.nix — the USER half of hyprland: glue for the plain lua
# config, plus hyprlock and hypridle. (Session/portal plumbing is system-side
# in modules/hyprland.nix.)
#
# The window-manager config itself is NOT here: it's the plain, tracked lua
# file home/hypr/hyprland.lua — symlinked, not Nix-generated, same rule as
# helix ("editor configs stay plain files"). This file only wires it up and
# exports the few values that must come from Nix.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  colors = import ./colors.nix;
  # hypr color formats want rrggbb without the leading '#'
  raw = c: lib.removePrefix "#" c;

  # Cursor theme/size come from home/cursor.nix (home.pointerCursor) — the
  # lua config sets XCURSOR_THEME/XCURSOR_SIZE from these via nix.lua below,
  # kept in sync automatically by reading the option.
  cursor = config.home.pointerCursor;
in
{
  # Hyprland 0.55 loads ~/.config/hypr/hyprland.lua INSTEAD of hyprland.conf
  # when it exists (hyprlang is deprecated). The home-manager
  # wayland.windowManager.hyprland module is deliberately NOT used: all it
  # would add over this symlink is the systemd session hook, which the lua
  # file carries by hand (see its ⚠ Load-bearing comment), and the
  # hyprland-session.target unit, declared below. The hyprland
  # package itself comes from the system module (programs.hyprland), so the
  # cap_sys_nice "Hyprland" wrapper stays in charge of the session.
  # NB: no activation hook either — after a rebuild inside a running
  # hyprland session, run `hyprctl reload` yourself.
  xdg.configFile."hypr/hyprland.lua".source = ./hypr/hyprland.lua;

  # Values the lua config reads via require("nix"): the melange palette
  # (home/colors.nix stays the single source of truth — never hardcode a hex
  # color in the lua file) and the cursor theme/size. Data only; all logic
  # stays in hyprland.lua where the lua LSP can see it.
  xdg.configFile."hypr/nix.lua".text = ''
    -- Generated by Nix (home/hyprland.nix). Do not edit — edit
    -- home/colors.nix (palette) or home/cursor.nix (cursor) instead.
    return ${
      lib.generators.toLua { } {
        colors = lib.mapAttrs (_: group: lib.mapAttrs (_: raw) group) colors;
        cursor = {
          inherit (cursor) name size;
        };
      }
    }
  '';

  # Hyprland ships official LuaLS annotation stubs for the whole hl.* API.
  # Symlinking them to a version-stable path lets .luarc.json (repo root —
  # it exists purely because of home/hypr/hyprland.lua) point
  # lua-language-server at them without chasing store paths across
  # hyprland bumps: that's what gives helix completion/hover/type checks
  # inside the lua config.
  xdg.configFile."hypr/stubs".source = "${pkgs.hyprland}/share/hypr/stubs";

  # ── xdph.conf — xdg-desktop-portal-hyprland (the screen-share portal) ───
  # Auto-grant "restore tokens": Chromium browsers request one on every
  # screen share (the "Allow a restore token" checkbox in the picker), and
  # granting it by default means the portal dialog appears only the FIRST
  # time a site shares — afterwards the token silently re-approves the same
  # source and only the browser's own picker shows. Without this, Meet
  # double-asks on every single share: Brave's tab/window/screen dialog PLUS
  # hyprland-share-picker on top of it. Tradeoff: a site you've shared with
  # once can re-capture that same source without the portal asking again
  # (picking a different source re-opens the dialog once). The portal reads
  # this at startup — after a rebuild, restart it or re-login:
  #   systemctl --user restart xdg-desktop-portal-hyprland
  xdg.configFile."hypr/xdph.conf".text = ''
    screencopy {
      allow_token_by_default = true
    }
  '';

  # ── hyprlock — themed lock screen ────────────────────────────────────────
  # PAM side is system-level (modules/hyprland.nix). hyprlock/hypridle
  # configs stay Nix-generated on purpose (unlike hyprland.lua): they're
  # hyprlang INI with interpolated palette colors and are never iterated on.
  programs.hyprlock = {
    enable = true;
    settings = {
      general.hide_cursor = true;
      animations.enabled = false; # matches the no-animations aesthetic

      background = [
        {
          monitor = "";
          color = "rgb(${raw colors.a.bg})";
        }
      ];

      input-field = [
        {
          monitor = "";
          size = "300, 60";
          outline_thickness = 2;
          rounding = 0;
          inner_color = "rgb(${raw colors.a.float})";
          outer_color = "rgb(${raw colors.a.ui})";
          font_color = "rgb(${raw colors.a.fg})";
          check_color = "rgb(${raw colors.b.green})";
          fail_color = "rgb(${raw colors.b.red})";
          capslock_color = "rgb(${raw colors.b.yellow})";
          # show how many unlock attempts have failed
          fail_text = "$FAIL ($ATTEMPTS)";
          placeholder_text = "";
          fade_on_empty = false;
        }
      ];
    };
  };

  # ── hyprland-session.target — the session anchor ────────────────────────
  # Since the HM hyprland module is deliberately NOT used (see the top of
  # this file), nothing generates this target for us — without it the lua
  # hook's `systemctl --user start hyprland-session.target` fails "unit not
  # found" and waybar + hypridle silently never start. The lua hook starts
  # it at compositor launch; BindsTo stops it when graphical-session.target
  # goes down at logout (both the plain and the uwsm-managed launch modes).
  # Deliberately NO Install section: the target must only ever be reached by
  # the lua hook's explicit start, not pulled in whenever a graphical
  # session appears — that's what scopes hypridle below to this compositor.
  systemd.user.targets.hyprland-session = {
    Unit = {
      Description = "hyprland compositor session";
      Documentation = [ "man:systemd.special(7)" ];
      BindsTo = [ "graphical-session.target" ];
      Wants = [ "graphical-session-pre.target" ];
      After = [ "graphical-session-pre.target" ];
    };
  };

  # ── hypridle — lock, screen off, and lock-before-sleep ──────────────────
  services.hypridle = {
    enable = true;
    # Scope to the hyprland session, not the default graphical-session.target:
    # any other graphical session (a future second compositor, a nested test
    # session) would start hypridle where it doesn't belong.
    systemdTarget = "hyprland-session.target";
    settings = {
      general = {
        # pidof-guard: loginctl lock-session, the SUPER+Escape bind, and
        # before_sleep can all fire this — never stack hyprlock instances.
        lock_cmd = "pidof hyprlock || hyprlock";
        # Lock BEFORE the system suspends (lid close, systemctl suspend…).
        before_sleep_cmd = "loginctl lock-session";
        # Screens back on when waking from suspend (DPMS state can stick).
        after_sleep_cmd = "hyprctl dispatch 'hl.dsp.dpms({ action = \"enable\" })'";
      };
      listener = [
        # 5 min idle → lock
        {
          timeout = 300;
          on-timeout = "loginctl lock-session";
        }
        # 10 min idle → screens off (back on when you touch anything)
        {
          timeout = 600;
          on-timeout = "hyprctl dispatch 'hl.dsp.dpms({ action = \"disable\" })'";
          on-resume = "hyprctl dispatch 'hl.dsp.dpms({ action = \"enable\" })'";
        }
      ];
    };
  };

  # Wayland desktop utilities used by the lua keybinds — they live here, not
  # in a shared file, so removing hyprland removes them atomically.
  home.packages = with pkgs; [
    grim # screenshot
    slurp # region selection
    wl-clipboard # wl-copy / wl-paste
    brightnessctl # backlight (keybinds above; PC just has no backlight device)
    # LSP for editing home/hypr/hyprland.lua — lives here, not helix.nix, so
    # removing hyprland removes it atomically. Helix picks it up for .lua by
    # default; .luarc.json at the repo root feeds it the hl.* stubs.
    lua-language-server
  ];
}
