# home/hyprland.nix — the USER half of hyprland: glue for the plain Lua
# config. (Session/portal plumbing is system-side in modules/hyprland.nix;
# the desktop shell — bar, lock screen, idle policy, notifications — is DMS,
# in modules/dms.nix.)
#
# The window-manager config itself is NOT here: it's the plain, tracked Lua
# file home/hypr/hyprland.lua — symlinked, not Nix-generated, same rule as
# the editor configs ("stay plain files"). This file only wires it up and
# exports the few values that must come from Nix.
{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  # The thumbnail-preview share picker (flake input, wired in flake.nix). Bound
  # once here so both the xdph.conf reference and home.packages use the same
  # store path. `inputs` reaches this file via home-manager.extraSpecialArgs.
  previewSharePicker =
    inputs.hyprland-preview-share-picker.packages.${pkgs.stdenv.hostPlatform.system}.default;
in
{
  # Hyprland 0.55+ loads ~/.config/hypr/hyprland.lua INSTEAD of
  # hyprland.conf whenever the .lua file exists (hyprlang is deprecated
  # upstream and will be dropped). NB: unlike niri, hyprland does NOT watch
  # the config — after editing, run `hyprctl reload` (or log out/in) to
  # pick it up.
  #
  # OUT-OF-STORE symlink (same rule and same hardcoded ~/nix-config base
  # path as home/neovim.nix — and the same silent failure mode: repo not at
  # ~/nix-config → dangling link, hyprland falls back to an autogenerated
  # config). A store symlink is NOT an option here: `dms setup` (the manual
  # first-login step) insists on writing this exact path — there is no flag
  # to skip the compositor config while still deploying the dms/*.lua
  # keybind fragments, and against a read-only store path it dies with
  # EROFS *before* deploying any fragment, leaving a session with no
  # keybinds at all. Writable symlink target = setup completes; its rewrite
  # of the tracked template lands in the git working tree, where
  # `git checkout -- home/hypr/hyprland.lua` discards it (do that BEFORE
  # any `git add .`). Upside of out-of-store: edits apply on a bare
  # `hyprctl reload`, no rebuild needed.
  xdg.configFile."hypr/hyprland.lua".source =
    config.lib.file.mkOutOfStoreSymlink
      "${config.home.homeDirectory}/nix-config/home/hypr/hyprland.lua";

  # (No Nix-generated Lua anymore: the old nix.lua that mirrored the cursor
  # theme/size into the compositor is gone — hyprland.lua stopped
  # require()ing it. The session cursor comes from home.pointerCursor's env
  # vars (home/cursor.nix); an in-compositor override belongs to the
  # DMS-owned dms/cursor.lua.)

  # xdph tuning (the screencast portal, modules/hyprland.nix). The portal reads
  # this at startup — `systemctl --user restart xdg-desktop-portal-hyprland`
  # after changing. DMS never touches xdph.conf, so a store symlink is safe.
  #
  # allow_token_by_default: auto-grant restore tokens, so a site/app that
  # already screenshared re-shares silently instead of re-opening the picker
  # every time (fixes the Meet/Brave double-picker annoyance). The preview
  # picker accepts xdph's `--allow-token` flag, so this behavior is preserved.
  #
  # custom_picker_binary: replace xdph's default hyprland-share-picker (a flat
  # Qt title list) with hyprland-preview-share-picker, which shows live
  # window/monitor THUMBNAILS. Referenced by ABSOLUTE store path, NOT the bare
  # name: xdph runs as a systemd user service, and the picker's one known
  # failure mode (`SHAREDATA returned selection -1`) is the binary not
  # resolving on PATH — an absolute path removes that class of bug. To revert
  # to the default Qt picker, comment out this one line.
  xdg.configFile."hypr/xdph.conf".text = ''
    screencopy {
      allow_token_by_default = true
      custom_picker_binary = ${previewSharePicker}/bin/hyprland-preview-share-picker
    }
  '';

  # ── hyprland-session.target — the session anchor ────────────────────────
  # Started explicitly by hyprland.lua's startup hook, stopped via BindsTo
  # when graphical-session.target goes down at logout. Deliberately NO
  # Install section — the target must only ever be reached by that explicit
  # start, never pulled in whenever a graphical session appears. That
  # scoping is what lets units like the DMS shell (dms.service, defined by
  # modules/dms.nix as a system-level user unit) belong to THIS session
  # specifically rather than to any graphical session that ever starts.
  systemd.user.targets.hyprland-session = {
    Unit = {
      Description = "hyprland compositor session";
      Documentation = [ "man:systemd.special(7)" ];
      BindsTo = [ "graphical-session.target" ];
      Wants = [ "graphical-session-pre.target" ];
      After = [ "graphical-session-pre.target" ];
    };
  };

  # (No idle daemon here: idle/lock/screen-off policy — and the locker
  # itself — is DMS. Timeouts are configured in the DMS Settings GUI, per
  # AC/battery. NB: they start UNSET on a fresh DMS state — set them on
  # first login or there is no idle lock.)

  # Utilities the session shells out to. No grim/slurp: screenshots go
  # through `dms screenshot`, piped into satty by the `screenshot-annotate`
  # wrapper (home/satty.nix; Print binds are the DEVIATION block at the
  # bottom of hypr/hyprland.lua). No
  # brightnessctl: brightness keys go through `dms ipc`. No playerctl
  # anymore either — the niri-era stock media binds used it, but DMS's
  # preset routes media keys through `dms ipc call mpris`.
  home.packages = with pkgs; [
    # Session-wide clipboard CLI: satty's copy-command, neovim's system
    # clipboard, and shell pipelines all exec wl-copy / wl-paste. Lives here
    # because it's Wayland-session infrastructure, not any one app's dep.
    wl-clipboard
  ]
  # The screencast picker (wired into xdph.conf above via absolute path). Also
  # installed on PATH here so it's runnable by hand for testing/debugging
  # (`hyprland-preview-share-picker --help`).
  ++ [ previewSharePicker ];
}
