# home/niri.nix — user half of niri: glue for the plain KDL config. The
# config itself is home/niri/config.kdl — symlinked, not Nix-generated (same
# "editor configs stay plain files" rule). System half: modules/niri.nix.
{
  config,
  pkgs,
  ...
}:

let
  cursor = config.home.pointerCursor;
in
{
  # OUT-OF-STORE symlink (hardcoded ~/nix-config path; wrong path = dangling
  # link and niri silently falls back to its built-in defaults). niri watches
  # the file and live-reloads on save — no rebuild, no reload command.
  # Individual files are linked, not the whole niri/ dir: ~/.config/niri must
  # stay a real writable directory because DMS writes its dms/ fragments
  # under it imperatively.
  xdg.configFile."niri/config.kdl".source =
    config.lib.file.mkOutOfStoreSymlink
      "${config.home.homeDirectory}/nix-config/home/niri/config.kdl";

  # No display config here: outputs are DMS-GUI-owned, written to the
  # untracked ~/.config/niri/dms/outputs.kdl.

  # The one Nix-GENERATED piece of niri config: the cursor, mirrored from
  # home.pointerCursor so home/cursor.nix's theme reaches the compositor
  # without being repeated. niri takes the cursor from config, not XCURSOR_*
  # env. Store symlink is fine: contents only change with a rebuild, and niri
  # notices the flipped symlink.
  xdg.configFile."niri/nix.kdl".text = ''
    // Generated by Nix (home/niri.nix) — edit home/cursor.nix instead.
    cursor {
        xcursor-theme "${cursor.name}"
        xcursor-size ${toString cursor.size}
    }
  '';

  # niri-session.target — the session anchor. Started explicitly by
  # config.kdl's spawn-at-startup line; deliberately NO Install section, so
  # session units (dms.service) belong to THIS session, not any graphical
  # session that ever appears. spawn-at-startup, not Wants= on niri.service:
  # niri runs spawns only AFTER importing WAYLAND_DISPLAY into the user
  # manager, so everything the target drags up is guaranteed to see the
  # display — a Wants= would race that import. Teardown needs no hook:
  # niri.service BindsTo graphical-session.target.
  systemd.user.targets.niri-session = {
    Unit = {
      Description = "niri compositor session";
      Documentation = [ "man:systemd.special(7)" ];
      BindsTo = [ "graphical-session.target" ];
      Wants = [ "graphical-session-pre.target" ];
      After = [ "graphical-session-pre.target" ];
    };
  };

  # No idle daemon here: idle/lock policy is DMS's, in GUI-owned settings
  # that DEFAULT TO 0 = never locks — a first-login Settings pass per
  # machine. No grim/slurp/brightnessctl/playerctl: screenshots, brightness
  # and media keys all go through DMS.
  home.packages = with pkgs; [
    # Session-wide clipboard CLI (satty's copy-command, nvim clipboard, shell
    # pipelines) — Wayland-session infrastructure, not one app's dep.
    wl-clipboard
  ];
}
