# home/niri.nix — the USER half of niri: glue for the plain KDL config.
# (Session/portal plumbing is system-side in modules/niri.nix; the desktop
# shell — bar, lock screen, idle policy, notifications — is DMS, in
# home/dms.nix.) Niri started as a side-by-side trial next to hyprland and
# won; it's the only session now.
#
# The window-manager config itself is NOT here: it's the plain, tracked
# KDL file home/niri/config.kdl — symlinked, not Nix-generated, same rule
# as the editor configs ("stay plain files"). This file only wires it up
# and exports the few values that must come from Nix.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  # Cursor theme/size come from home/cursor.nix (home.pointerCursor) — the
  # generated nix.kdl below feeds them to niri's cursor section, kept in
  # sync automatically by reading the option.
  cursor = config.home.pointerCursor;
in
{
  # niri reads ~/.config/niri/config.kdl. NB: no reload hook needed —
  # niri watches the config (and every include) and live-reloads when the
  # store symlink flips after a rebuild.
  xdg.configFile."niri/config.kdl".source = ./niri/config.kdl;

  # The one value config.kdl still pulls in via its `include`: the cursor
  # theme/size, mirrored from home.pointerCursor. All COLORS left this file
  # with the DMS migration — niri's focus-ring/backdrop colors now come from
  # ~/.config/niri/dms/colors.kdl, which dms (re)generates from the
  # wallpaper (matugen) and config.kdl includes alongside this one.
  xdg.configFile."niri/nix.kdl".text = ''
    // Generated by Nix (home/niri.nix). Do not edit — edit
    // home/cursor.nix instead.
    cursor {
        xcursor-theme "${cursor.name}"
        xcursor-size ${toString cursor.size}
    }
  '';

  # ── niri-session.target — the session anchor ────────────────────────────
  # Started explicitly by config.kdl's spawn-at-startup, stopped via BindsTo
  # when graphical-session.target goes down at logout. Deliberately NO
  # Install section — the target must only ever be reached by that explicit
  # start, never pulled in whenever a graphical session appears. That
  # scoping is what lets units like the DMS shell (home/dms.nix) belong to
  # THIS session specifically rather than to any graphical session that
  # ever starts.
  systemd.user.targets.niri-session = {
    Unit = {
      Description = "niri compositor session";
      Documentation = [ "man:systemd.special(7)" ];
      BindsTo = [ "graphical-session.target" ];
      Wants = [ "graphical-session-pre.target" ];
      After = [ "graphical-session-pre.target" ];
    };
  };

  # (No idle daemon here anymore: idle/lock/screen-off policy — and the
  # locker itself — moved into DMS with the 2026-07 migration. Timeouts are
  # configured in the DMS Settings GUI, per AC/battery; DMS listens for
  # `loginctl lock-session` and locks before suspend on its own. NB: the
  # idle timeouts start UNSET on a fresh DMS state — set them on first
  # login or there is no idle lock.)

  # Utilities the session shells out to. No grim/slurp here on purpose: the
  # stock config uses niri's built-in screenshot UI (Print/Ctrl+Print/
  # Alt+Print). No brightnessctl either — the brightness keys go through
  # `dms ipc`, and brightness handling is built into the dms binary.
  home.packages = with pkgs; [
    playerctl # stock XF86AudioPlay/Stop/Prev/Next binds
    # Session-wide clipboard CLI: satty's copy-command, neovim's system
    # clipboard, and shell pipelines all exec wl-copy / wl-paste. Lives here
    # because it's Wayland-session infrastructure, not any one app's dep.
    wl-clipboard

    # Backs the Mod+E bind in config.kdl: set every column on the focused
    # workspace to an equal 100/N % width (3 columns → thirds, 2 → halves).
    # A script because niri has NO built-in "resize all columns" action —
    # set-column-width and the presets only touch the focused column, so we
    # walk the columns over `niri msg` instead. Percent changes go through
    # the same gaps-aware proportion math as preset-column-widths, which is
    # why N columns at 100/N % fit the output exactly.
    # `niri` itself is deliberately NOT in runtimeInputs: the session
    # already has the real compositor's binary on PATH, and pinning a
    # second copy here could let `niri msg` version-skew from the running
    # compositor.
    (pkgs.writeShellApplication {
      name = "niri-equalize-columns";
      runtimeInputs = [ pkgs.jq ];
      text = ''
        ws=$(niri msg --json workspaces | jq '.[] | select(.is_focused).id')
        # One representative window per column: windows stacked in a column
        # share its width, so dedupe by column index (layout.
        # pos_in_scrolling_layout[0]) and set each column once. Floating
        # windows are excluded — they don't occupy a column.
        ids=$(niri msg --json windows | jq -r --argjson ws "$ws" '
          [ .[] | select(.workspace_id == $ws and (.is_floating | not)) ]
          | unique_by(.layout.pos_in_scrolling_layout[0]) | .[].id')
        n=$(wc -w <<< "$ids")
        [ "$n" -eq 0 ] && exit 0
        pct=$(awk "BEGIN { printf \"%.4f\", 100 / $n }")
        while read -r id; do
          niri msg action set-window-width --id "$id" "$pct%"
        done <<< "$ids"
      '';
    })
  ];
}
