-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "2880x1800@120.000", position = "0x0", scale = 1.6, vrr = 0 })
