-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/
--
-- Fully OURS since the 2026-07 Noctalia migration (under DMS this file
-- tracked the shell's autogenerated template; Noctalia writes no
-- compositor config, so there is no template to track). Loaded pieces:
--   require("binds")         — keybinds, tracked (home/hypr/binds.lua)
--   require("local.outputs") — THIS machine's monitors, gitignored,
--                              hand-maintained (home/hypr/local/)
--   require("noctalia")      — border colors, written by noctalia's
--                              hyprland template on every palette change
-- Edits here apply on `hyprctl reload` (hyprland does not watch the file).

hl.config({ autogenerated = false })

-- Session plumbing, startup half: push the env and start the session
-- target as ONE sh -c command. Two independent spawns is a race — if the
-- target start wins, noctalia.service comes up without WAYLAND_DISPLAY and
-- the shell is dead until a manual restart. `&&` in one shell forces the
-- env push to land in the systemd user manager BEFORE anything binds to
-- the target.
hl.on("hyprland.start", function()
	hl.exec_cmd(
		"sh -c 'dbus-update-activation-environment --systemd --all && systemctl --user start hyprland-session.target'"
	)
end)

-- Session plumbing, shutdown half: tear the session down when the
-- compositor exits. Without this, after a logout the user manager keeps
-- the dead session's WAYLAND_DISPLAY and the next login finds the shell &
-- friends still "running" against a vanished socket — the classic
-- broken-shell-after-relogin. Stopping graphical-session.target propagates
-- everywhere: hyprland-session.target (BindsTo), noctalia (PartOf
-- hyprland-session.target), plasma-kwallet-pam (PartOf graphical-
-- session.target). The next login's startup hook restarts them all with a
-- fresh env. Keep both halves paired.
hl.on("hyprland.shutdown", function()
	hl.exec_cmd("systemctl --user stop graphical-session.target hyprland-session.target")
end)

hl.config({
	input = {
		-- MACHINE FACT: US + Thai. Binds resolve against the FIRST layout,
		-- so SUPER binds keep working under the Thai layout. Switching is
		-- the Ctrl+Space bind below — deliberately NOT a `grp:` xkb option
		-- (the two mechanisms must never coexist).
		kb_layout = "us,th",
		numlock_by_default = true,
		-- Focus follows the mouse: hovering a window focuses it (0 was
		-- click-to-focus).
		follow_mouse = 1,
		-- Natural scrolling on mice too (the touchpad option below only
		-- covers touchpads; without this the PC's mouse wheel scrolls the
		-- traditional direction while the thinkpad's touchpad doesn't)
		natural_scroll = true,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		-- Gaps/shadow/blur follow Noctalia's recommended compositor
		-- settings (docs.noctalia.dev/v5/compositor-settings/hyprland/),
		-- replacing the DMS-era template values that survived the 2026-07
		-- migration. Anything else the docs don't set (animations, opacity)
		-- is deliberately left at Hyprland's defaults.
		gaps_in = 5,
		gaps_out = 10,
		-- Hyprland's default 1 px focus border is too thin to spot; 2 px
		-- matches what this setup always ran, and eyeballing 3 and 4 px
		-- read as a frame, not a focus hint (colors come from noctalia's
		-- template, required at the bottom of this file).
		border_size = 2,
		resize_on_border = false,
		layout = "dwindle",
	},
	decoration = {
		-- Noctalia's docs recommend 20, but that read too round in
		-- practice (and so did 12, the old GNOME-app window rule's value,
		-- which that deviation had made redundant); 8 is deliberate.
		rounding = 8,
		rounding_power = 2,
		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},
		-- Window blur (Noctalia's shell surfaces get theirs from the
		-- layer rule below, which works even without this block).
		blur = {
			enabled = true,
			size = 3,
			passes = 2,
			vibrancy = 0.1696,
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- MACHINE FACT: the PC's outputs are 4K at scale 1.5 (see local/outputs.lua
-- on that machine). Without this, XWayland apps (Steam, other X11) render
-- at the logical resolution and Hyprland bitmap-upscales them 1.5x =>
-- blurry. force_zero_scaling makes XWayland own native pixels (crisp);
-- per-app scaling then restores correct size (Steam: STEAM_FORCE_DESKTOPUI_
-- SCALING in modules/gaming.nix). Harmless on the thinkpad if it runs at
-- scale 1 (zero scaling == no scaling there).
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- MACHINE FACT: keyboard-layout toggle on Ctrl+Space, same key as the niri
-- setup. Hyprland 0.55's Lua dispatcher table has no xkb-layout entry —
-- the mechanism is hyprctl. `all` (not `current`) keeps every keyboard in
-- sync: the thinkpad's internal, externals, AND kanata's virtual keyboard,
-- mirroring niri's applies-to-every-keyboard behavior. No reverse-cycle
-- bind on purpose: with two layouts, `next` IS the toggle.
hl.bind("CTRL + space", hl.dsp.exec_cmd("hyprctl switchxkblayout all next"))

-- Snappy animations. Hyprland's built-in fallback is ONE `global` tree
-- node at speed 8 (800 ms) — every animation inherits it, and it feels
-- sluggish. `speed` is in deciseconds (2 = 200 ms). Overriding `global`
-- retunes everything at once (unset leaves inherit the nearest set
-- ancestor); the leaves below get faster still. The curve must be
-- registered BEFORE the hl.animation calls that name it — only "default"
-- and "linear" exist without registration. cubic-bezier(0.15, 0, 0.1, 1)
-- starts fast and eases out hard, which is what reads as "snappy".
-- Beware: hl.animation silently ignores misspelled field names.
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 2.5, bezier = "quick" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2, bezier = "quick" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.5, bezier = "quick" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.8, bezier = "quick" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.5, bezier = "quick" })
hl.animation({ leaf = "border", enabled = true, speed = 2, bezier = "quick" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })

-- Noctalia's surfaces (upstream's recommended rules from its Hyprland
-- docs): no animations on shell layers, blur behind the translucent ones,
-- and xray on the bar (the DMS-era bar had it too — the bar shows the
-- wallpaper through gaps, not the windows under it). The shell's own
-- windows (Settings…) float.
hl.layer_rule({
	match = { namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$" },
	no_anim = true,
	ignore_alpha = 0.5,
	blur = true,
	blur_popups = true,
})
hl.layer_rule({ match = { namespace = "^noctalia-bar-.+$" }, xray = true })
hl.window_rule({
	match = { class = "^(dev\\.noctalia\\.Noctalia)$" },
	float = true,
	size = { 1080, 920 },
})

require("binds") -- tracked: home/hypr/binds.lua
require("local.outputs") -- machine-local monitors: home/hypr/local/ (gitignored)

-- Border colors from the wallpaper palette: noctalia's hyprland template
-- renders ~/.config/hypr/noctalia.lua (a module exporting apply_theme) on
-- every palette change, and the colors_changed hook in
-- home/noctalia/config.toml runs `hyprctl reload` so it takes effect.
-- Guarded because the file starts as an EMPTY placeholder (seeded by
-- home/noctalia.nix — require() on an empty chunk returns `true`, not a
-- table) until the first wallpaper is picked. The literal require("noctalia")
-- call below doubles as the marker the template's apply.sh greps for —
-- without it, the shell would append its own require line to this file.
local ok, noctalia = pcall(function()
	return require("noctalia")
end)
if ok and type(noctalia) == "table" then
	noctalia.apply_theme()
end

-- MACHINE FACTS: pin workspaces to monitors, per host.
-- PC: 1-5 on the Alienware (main, horizontal), 6-9 on the vertical Dell.
-- Thinkpad: 1-5 on the built-in panel, 6-10 on the docked Dell above it.
-- Externals matched by DESCRIPTION, not DP port: ports can renumber
-- across replugs/BIOS updates. Guarded by HOSTNAME because desc rules
-- for absent monitors are NOT no-ops: on the thinkpad the PC's rules
-- claimed workspaces 1-9 as "belonging elsewhere", so eDP-1's default
-- workspace became 10 instead of 1. `default` on 1 and 6 makes each
-- monitor start on its first bound workspace at login/monitor-connect.
local f = io.open("/etc/hostname")
local host = f and f:read("*l") or ""
if f then
	f:close()
end

if host == "unclebeam-pc" then
	local main = "desc:Dell Inc. AW2725Q 4KTF174" -- Alienware, horizontal
	local secondary = "desc:Dell Inc. DELL S2725QS 3V7S364" -- Dell, vertical
	for ws = 1, 5 do
		hl.workspace_rule({ workspace = tostring(ws), monitor = main, default = (ws == 1) })
	end
	for ws = 6, 9 do
		hl.workspace_rule({ workspace = tostring(ws), monitor = secondary, default = (ws == 6) })
	end
elseif host == "unclebeam-thinkpad" then
	-- eDP-1 by connector (built-in, never renumbers); Dell by description
	-- (USB-C dock ports do — the U3225QE came up as DP-5, the U2725QE as
	-- DP-1). When the Dell is unplugged its workspaces just fall back to
	-- eDP-1; the absent-monitor bug above needed the internal panel's OWN
	-- workspaces claimed elsewhere, and 1-5 are pinned right here, so
	-- eDP-1's default stays 1.
	local internal = "eDP-1"
	-- A PREFIX, deliberately: `desc:` is compared with starts_with (hyprland's
	-- CMonitor::matchesStaticSelector), so "Dell Inc. DELL U" catches whichever
	-- docked Dell is plugged in — U3225QE 27D4834 or U2725QE 5R1YC34. Two rules
	-- for the same workspace would NOT work as an alternative: the FIRST match
	-- wins and the second is silently dropped, so the absent monitor's rule
	-- would win half the time. Safe across hosts: this branch is hostname-
	-- guarded, and both of the PC's Dell-branded panels are outside this
	-- prefix anyway — "Dell Inc. AW2725Q …" and "Dell Inc. DELL S2725QS …".
	-- Keep the "DELL U" in mind if a Dell U-series ever lands on the PC.
	local external = "desc:Dell Inc. DELL U"
	for ws = 1, 5 do
		hl.workspace_rule({ workspace = tostring(ws), monitor = internal, default = (ws == 1) })
	end
	for ws = 6, 10 do
		hl.workspace_rule({ workspace = tostring(ws), monitor = external, default = (ws == 6) })
	end
end
