-- home/hypr/hyprland.lua — THE hyprland config, a plain Lua file symlinked
-- to ~/.config/hypr/hyprland.lua by home/hyprland.nix (same "editor configs
-- stay plain files" rule as nvim). Hyprland 0.55+ loads hyprland.lua
-- INSTEAD of hyprland.conf when it exists; hyprland does NOT watch the
-- file, so after a rebuild run `hyprctl reload`.
--
-- This file deliberately TRACKS DMS'S RECOMMENDED TEMPLATE (the file
-- `dms setup` would generate, embedded in the DMS package) — NOT the
-- pre-niri personalized hyprland config, and NOT hyprland's bare example.
-- Deviations are limited to machine facts (keyboard layouts), session
-- plumbing, and Nix-fed values, each marked with a DEVIATION comment.
-- Everything else — keybinds, layout, colors, cursor, monitors, window
-- rules — belongs to the required dms.* fragments at the bottom, owned by
-- `dms setup` and the DMS Settings GUI (never Nix, never this file).

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
-- SESSION PLUMBING (deviation from the template, same effect): the
-- template runs the env push and the target start as TWO separate spawns,
-- which can race. Chained with && instead, because the ordering is
-- load-bearing: plasma-kwallet-pam (modules/kwallet.nix) is After=
-- graphical-session.target and needs the FRESH WAYLAND_DISPLAY already in
-- the systemd user env when the target comes up — ksecretd aborts on a
-- stale socket. hyprland-session.target itself is declared in
-- home/hyprland.nix (BindsTo graphical-session.target, no [Install]).
-- NEVER add a `dms run` spawn here — the shell runs as a user service
-- hanging off that target (home/dms.nix) and must not run twice.
hl.on("hyprland.start", function()
	hl.exec_cmd(
		"dbus-update-activation-environment --systemd --all"
			.. " && systemctl --user start hyprland-session.target"
	)
end)
-- DMS_STARTUP_END

-- DEVIATION (Nix-fed cursor): theme/size mirrored from home.pointerCursor
-- via the generated ~/.config/hypr/nix.lua (home/hyprland.nix). The
-- dms.cursor fragment loads later and overrides these once a cursor is
-- picked in the DMS Settings GUI — this is only the first-run baseline.
local nix = require("nix")
hl.env("XCURSOR_THEME", nix.cursor.name)
hl.env("XCURSOR_SIZE", tostring(nix.cursor.size))

hl.config({
	input = {
		-- MACHINE FACT (deviation): US + Thai. The template leaves kb_layout
		-- empty (inherits XKB_DEFAULT_LAYOUT). Binds resolve against the
		-- FIRST layout, so SUPER binds keep working under the Thai layout.
		-- Switching is the Ctrl+Space bind below — deliberately NOT a
		-- `grp:` xkb option (the two mechanisms must never coexist).
		kb_layout = "us,th",
		numlock_by_default = true,
		follow_mouse = 0,
		-- DEVIATION: natural scroll on mice/trackpoint too, matching the
		-- niri setup — the template only sets it for the touchpad.
		natural_scroll = true,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- DEVIATION (machine fact): keyboard-layout toggle on Ctrl+Space, same key
-- as the niri setup. Hyprland 0.55's Lua dispatcher table has no xkb-layout
-- entry — the mechanism is hyprctl. `all` (not `current`) keeps every
-- keyboard in sync: the thinkpad's internal, externals, AND kanata's
-- virtual keyboard, mirroring niri's applies-to-every-keyboard behavior.
hl.bind("CTRL + space", hl.dsp.exec_cmd("hyprctl switchxkblayout all next"))
hl.bind("CTRL + SHIFT + space", hl.dsp.exec_cmd("hyprctl switchxkblayout all prev"))

-- NB: NO monitor lines here, on purpose — monitors are DMS's to manage:
-- the Settings GUI's Displays page writes ~/.config/hypr/dms/outputs.lua
-- (required below), the hyprland-era counterpart of "DMS settings live in
-- its GUI, not in Nix". Configure the layout there on first login; the
-- niri-era values for reference live in the migration plan / git history
-- of home/niri/config.kdl.

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

-- The DMS-owned fragments — keybinds (dms ipc, screenshots, workspaces),
-- matugen colors, GUI-configured monitors/cursor/window-rules. Order is
-- load-bearing: they load LAST so GUI-made settings override this file's
-- defaults. All seven exist from first rebuild (home/dms.nix's activation
-- script, which runs `dms setup` to seed DMS's real defaults into the
-- missing-or-empty ones — no manual first-login step) — an empty Lua chunk
-- loads fine, a MISSING file would hard-fail the whole config.
require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
