-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	-- DEVIATION (session plumbing): the DMS template fires these as two
	-- independent spawns, which is a race — if the target start wins,
	-- dms.service comes up without WAYLAND_DISPLAY and the shell is dead
	-- until a manual restart. `&&` in one shell forces the env push to
	-- land in the systemd user manager BEFORE anything binds to the target.
	hl.exec_cmd(
		"sh -c 'dbus-update-activation-environment --systemd --all && systemctl --user start hyprland-session.target'"
	)
end)
-- DMS_STARTUP_END

-- DEVIATION (session plumbing): tear the session down when the compositor
-- exits. The template only ever STARTS hyprland-session.target, so after a
-- logout the user manager keeps the dead session's WAYLAND_DISPLAY and the
-- next login finds dms & friends still "running" against a vanished socket
-- — the classic broken-shell-after-relogin. Stopping graphical-session.
-- target propagates everywhere: hyprland-session.target (BindsTo), dms
-- (PartOf hyprland-session.target), plasma-kwallet-pam (PartOf graphical-
-- session.target). The next login's startup hook restarts them all with a
-- fresh env. Kept OUTSIDE the DMS_STARTUP markers so a `dms setup` rewrite
-- + `git checkout` round-trip never touches it.
hl.on("hyprland.shutdown", function()
	hl.exec_cmd("systemctl --user stop graphical-session.target hyprland-session.target")
end)

hl.config({
	input = {
		-- MACHINE FACT (deviation): US + Thai. The template leaves kb_layout
		-- empty (inherits XKB_DEFAULT_LAYOUT). Binds resolve against the
		-- FIRST layout, so SUPER binds keep working under the Thai layout.
		-- Switching is the Ctrl+Space bind below — deliberately NOT a
		-- `grp:` xkb option (the two mechanisms must never coexist).
		kb_layout = "us,th",
		numlock_by_default = true,
		follow_mouse = 0,
		-- DEVIATION: natural scrolling on mice too (the touchpad option below
		-- only covers touchpads; without this the PC's mouse wheel scrolls
		-- the traditional direction while the thinkpad's touchpad doesn't)
		natural_scroll = true,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = true,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

-- DEVIATION (machine fact): both this host's outputs are 4K at scale 1.5
-- (see dms/outputs.lua). Without this, XWayland apps (Steam, other X11)
-- render at the logical resolution and Hyprland bitmap-upscales them 1.5x
-- => blurry. force_zero_scaling makes XWayland own native pixels (crisp);
-- per-app scaling then restores correct size (Steam: STEAM_FORCE_DESKTOPUI_
-- SCALING in modules/gaming.nix). Harmless on the thinkpad if it runs at
-- scale 1 (zero scaling == no scaling there).
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- DEVIATION (machine fact): keyboard-layout toggle on Ctrl+Space, same key
-- as the niri setup. Hyprland 0.55's Lua dispatcher table has no xkb-layout
-- entry — the mechanism is hyprctl. `all` (not `current`) keeps every
-- keyboard in sync: the thinkpad's internal, externals, AND kanata's
-- virtual keyboard, mirroring niri's applies-to-every-keyboard behavior.
-- No reverse-cycle bind on purpose: with two layouts, `next` IS the toggle.
hl.bind("CTRL + space", hl.dsp.exec_cmd("hyprctl switchxkblayout all next"))

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

-- DEVIATION (mandatory feature): screenshot → satty annotation. These
-- binds live HERE, not in the dms.* fragments, so they exist on a fresh
-- install and can't be lost to a Settings-GUI rewrite of binds-user.lua.
-- Must stay BELOW the require()s: hl.unbind removes the DMS template's
-- Print binds (which exist only after dms.binds loads — duplicate binds
-- fire BOTH dispatchers), and loading last means these always win.
-- screenshot-annotate is the wrapper from home/satty.nix.
hl.unbind("Print")
hl.unbind("CTRL + Print")
hl.unbind("ALT + Print")
hl.bind("Print", hl.dsp.exec_cmd("screenshot-annotate"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("screenshot-annotate full"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("screenshot-annotate window"))

-- DEVIATION (machine fact, unclebeam-pc): pin workspaces to monitors.
-- 1-5 live on the MSI (main, horizontal), 6-9 on the vertical Gigabyte.
-- Matched by DESCRIPTION, not DP port: ports can renumber across
-- replugs/BIOS updates, and on the thinkpad neither description exists,
-- so these rules are harmless no-ops there (workspaces behave as before).
-- `default` on 1 and 6 makes each monitor start on its first bound
-- workspace at login/monitor-connect.
local main = "desc:Micro-Star Int'l Co. Ltd. PM271UPXW12G 0x01010101" -- MSI, horizontal
local secondary = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. M28U 22060B005352" -- Gigabyte, vertical
for ws = 1, 5 do
	hl.workspace_rule({ workspace = tostring(ws), monitor = main, default = (ws == 1) })
end
for ws = 6, 9 do
	hl.workspace_rule({ workspace = tostring(ws), monitor = secondary, default = (ws == 6) })
end
